### ISSUE TITLE
MQTT to ROS doesn't work, but ROS to MQTT works

### ISSUE THREAD

**Issue by mhaboali** [groove-x/mqtt_bridge#33]
I've tried the example to publish /ping topic and I managed to get the msgs on the other MQTT app, but the /pong topic was empty.

Any help? @yuma-m

**Comment by yuma-m** [comment]
Hi @mhaboali,
Could you show your ROS logs?
If you are using the demo configuration below, I think the message sent to ROS `/ping` topic will be sent back to ROS `/pong` topic because they use the common MQTT topic `ping`.
https://github.com/groove-x/mqtt_bridge/blob/master/config/demo_params.yaml#L13-L20

**Comment by ledmonster** [comment]
@mhaboali Please reopen the issue if you have extra questions, thanks.
